name: Azure Static Web App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./client
        run: |
          npm ci

      - name: Build client (production)
        working-directory: ./client
        env:
          # If you prefer, set these as GitHub repository secrets and reference them here.
          # But VITE_API_URL is not secret (it's the public AppService URL).
          VITE_API_URL: ${{ secrets.VITE_API_URL }}            # optional: set these in repo Secrets
          VITE_CLIENT_URL: ${{ secrets.VITE_CLIENT_URL }}
          VITE_PUBLIC_CALLBACK_URL: ${{ secrets.VITE_PUBLIC_CALLBACK_URL }}
        run: |
          npm run build

      - name: Upload to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_ISLAND_04D32840F }}
          action: "upload"
          app_location: "client"
          api_location: ""
          output_location: "client/dist"

