name: Azure Web App CI/CD

on:
  push:
    branches: [ main ]    # change to your branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install
        run: npm ci

      - name: Build (if needed)
        run: npm run build --if-present

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v4
        with:
          app-name: ivr-app-linux                # << replace with your app name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
