name: CI/CD — build & deploy to Azure Web App (Linux)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      # adjust this if your package.json is not in repo root
      WORKDIR: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout (debug)
        run: |
          echo "PWD: $PWD"
          echo "--- root listing ---"
          ls -la
          echo "--- listing $WORKDIR ---"
          if [ -d "$WORKDIR" ]; then ls -la "$WORKDIR"; else echo "$WORKDIR does not exist"; fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies (use ci if lockfile exists)
        working-directory: ${{ env.WORKDIR }}
        run: |
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json — running npm ci"
            npm ci --prefer-offline --no-audit --loglevel=error
          else
            echo "No lockfile — running npm install"
            npm install --prefer-offline --no-audit --loglevel=error
          fi

      - name: Build (if you have a build script)
        working-directory: ${{ env.WORKDIR }}
        run: npm run build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ivr-app-linux
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.WORKDIR }}

